web/router.ex
defmodule Exsite.Router do
  use Exsite.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Exsite.Auth, repo: Exsite.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/api", Exsite do
    pipe_through :api
    delete "/sessions/:user_id", SessionController, :delete
    post "/images", ImageController, :create
    post "/comments/:comment_id/replies", ReplyController, :create
  end

  scope "/", Exsite do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController,
      only: [:index, :show, :new, :create] do
      get "/:tab_key", UserController, :show, as: :tab
    end
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/topics", TopicController
    resources "/posts", PostController do
      resources "/comments", CommentController, only: [:create, :update, :delete]
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", Exsite do
  #   pipe_through :api
  # end
end

web/models/post.ex
defmodule Exsite.Post do
  use Exsite.Web, :model
  use Ecto.Schema

  schema "posts" do
    field :title, :string
    field :content, :string
    field :content_format, :string, default: "markdown"
    field :last_commented_at, Timex.Ecto.DateTime
    field :last_comment_user_id, :integer
    field :state, :integer, default: 0
    field :commentes_count, :integer, default: 0
    field :favorates_count, :integer, default: 0
    field :suggested_at, Timex.Ecto.DateTime
    field :deleted_at, Timex.Ecto.DateTime
    belongs_to :user, Exsite.User
    belongs_to :topic, Exsite.Topic
    has_many :comments, Exsite.Comment
    has_many :replies, through: [:comments, :replies]

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  @required_fields [
    :title,
    :content,
    :user_id,
    :topic_id]

  @cast_fields @required_fields ++ [
    :state,
    :last_commented_at,
    :last_comment_user_id,
    :commentes_count,
    :favorates_count,
    :suggested_at,
    :suggested_at,
    :deleted_at]

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @cast_fields)
    |> validate_required(@required_fields)
  end
end

web/controllers/post_controller.ex
defmodule Exsite.PostController do
  require IEx
  use Exsite.Web, :controller
  alias Exsite.{Post, Comment}
  alias Exsite.Bll.{PostBll, TopicBll}
  plug :authenticate_user when action in [:new, :create, :edit, :update]

  def index(conn, _params) do
    posts = Post |> Repo.all
    conn
    |> assign(:posts, posts)
    |> render("index.html")
  end

  def new(conn, _params) do
    changeset = Post.changeset(%Post{})
    root_topics = TopicBll.root_topics
    conn
    |> assign(:changeset, changeset)
    |> assign(:root_topics, root_topics)
    |> render("new.html")
  end

  def create(conn, %{"post" => post_params}) do
    post_params =
      post_params
      |> Map.merge(%{"user_id" => get_session(conn, :user_id)})

    case PostBll.create(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "post created")
        |> redirect(to: post_path(conn, :show, post))

      {:error, changeset} ->
        render(conn, "new.html",
          changeset: changeset,
          root_topics: TopicBll.root_topics)
    end
  end

  def show(conn, %{"id" => id}) do
    post =
      Post
      |> preload([:topic, :user, :comments, comments: [
          :user, :replies, replies: [:user, :reply, reply: :user]]])
      |> Repo.get(id)
    changeset = Comment.changeset(%Comment{})
    render conn, "show.html", post: post, changeset: changeset
  end

  def edit(conn, %{"id" => id}) do
    root_topics = TopicBll.root_topics
    post =
      Post
      |> preload([:topic, :user])
      |> Repo.get!(id)

    changeset = Post.changeset(post)
    conn
    |> assign(:post, post)
    |> assign(:changeset, changeset)
    |> assign(:root_topics, root_topics)
    |> render("edit.html")
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Post |> Repo.get(id)
    changeset = post |> Post.changeset(post_params)
    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "post update")
        |> redirect(to: post_path(conn, :show, post))

      {:error, changeset} ->
        render(conn, "edit.html",
          post: post,
          changeset: changeset,
          root_topics: TopicBll.root_topics)
    end
  end
end

web/views/post_view.ex
defmodule Exsite.PostView do
  use Exsite.Web, :view

  alias Exsite.User

  def current_user do
    @current_user
  end

  def current_user? do
    case @current_user do
      %User{} -> true
      nil -> false
    end
  end
end

web/templates/post/edit.html.eex
<h2>Edit post</h2>

<%= render "form.html",
      changeset: @changeset,
      post: @post,
      conn: @conn,
      root_topics: @root_topics,
      action: post_path(@conn, :update, @post)
%>

<%= link "Back", to: post_path(@conn, :index) %>

web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-default selected-topic" type="button"
          data-toggle="modal" data-target="#topic-selector">
          <%=
            if @post do
              @post.topic.name
            else
              "选择节点"
            end
          %>
        </button>
      </span>
      <%= hidden_input f, :topic_id %>
      <%= text_input f, :title, placeholder: "输入标题",class: "form-control" %>
    </div>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= textarea f, :content, class: "form-control simplemde" %>
    <%= error_tag f, :content %>
  </div>

  <div class="form-group">
    <label for="file" class="btn btn-default">上传</label>
    <%= if is_nil @post do %>
      <%= submit "发布", class: "btn btn-primary" %>
    <% else %>
      <%= submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

 <%= form_for @conn, image_path(@conn, :create),
   [as: :upload,
    multipart: true,
    id: "upload-form",
    name: "upload"], fn f -> %>
   <div class="form-group">
     <%= file_input f, :file,
        id: "file",
        class: "form-control file-input" %>
   </div>
 <% end %>

<!-- modal 弹层 -->
<div class="modal fade" id="topic-selector" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">选择节点</h4>
      </div>
      <div class="modal-body">
        <div class="topic-list">
          <%= for topic  <- @root_topics do %>
            <div class="media topic">
              <div class="media-left">
                <label><%= topic.name %></label>
              </div>
              <div class="media-body">
                <%= for child <- topic.children do %>
                  <span class="name" data-id="<%= child.id %>"><a><%= child.name %></a></span>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

web/templates/post/index.html.eex
<h2>Listing posts</h2>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>Content format</th>
      <th>Last commented at</th>
      <th>Last comment user</th>
      <th>Topic</th>
      <th>State</th>
      <th>Commentes count</th>
      <th>Favorates count</th>
      <th>Suggested at</th>
      <th>Deleted at</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= post.user_id %></td>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= post.content_format %></td>
      <td><%= post.last_commented_at %></td>
      <td><%= post.last_comment_user_id %></td>
      <td><%= post.topic_id %></td>
      <td><%= post.state %></td>
      <td><%= post.commentes_count %></td>
      <td><%= post.favorates_count %></td>
      <td><%= post.suggested_at %></td>
      <td><%= post.deleted_at %></td>

      <td class="text-right">
        <%= link "Show", to: post_path(@conn, :show, post), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: post_path(@conn, :edit, post), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New post", to: post_path(@conn, :new) %>

web/templates/post/new.html.eex
<h2>发布话题</h2>

<%= render "form.html", changeset: @changeset,
                        post: nil,
                        conn: @conn,
                        root_topics: @root_topics,
                        action: post_path(@conn, :create) %>

<%= link "Back", to: post_path(@conn, :index) %>

web/templates/post/show.html.eex
<div class="col-md-9">
  <h2><%= @post.title %></h2>
  <div>
    <small class="info">
      <%= link @post.topic.name,
            to: topic_path(@conn, :show, @post.topic),
            class: "topic-link" %>
      <%= link @post.user.nickname,
            to: user_path(@conn, :show, @post.user),
            class: "user-link" %>
      <%= time_formatter @post.inserted_at %>
    </small>
  </div>
  <hr>
  <article class="article">
    <%= raw Earmark.as_html!(@post.content) %>
  </article>
  <hr>

  <div>
    <a type="button" class="btn btn-default btn-sm">收藏</a>
    <a type="button" class="btn btn-default btn-sm">举报</a>
    <%= if !is_nil(@current_user)
      and @current_user.id == @post.user_id do %>
      <%= link "编辑",
        to: post_path(@conn, :edit, @post),
        class: "btn btn-default btn-sm" %>
    <% end %>
  </div>

  <div class="comments">
    <%= if length(@post.comments) > 0 do %>
      <h4 class="title">评论</h4>
      <ul class="media-list">
        <%= for comment <- @post.comments do %>
          <li class="media">
            <%= if is_nil(comment.deleted_at) do %>
              <div class="media-left">
                <% link to: user_path(@conn, :show, comment.user) do %>
                  <img class="" src="images/phoenix.png" alt="avatar">
                <% end %>
              </div>

              <div class="media-body">
                <small class="info">
                  <a class="topic-link"
                     href="#<%= comment.floor_number %>"
                     name="<%= comment.floor_number %>">
                    <b><%= comment.floor_number %>楼</b>
                  </a>
                  <%= link comment.user.nickname,
                      to: user_path(@conn, :show, comment.user),
                      class: "user-link" %>
                  <%= time_formatter comment.inserted_at %>
                </small>
                <article>
                  <%= raw Earmark.as_html!(comment.content) %>
                </article>

                <%= if !is_nil(@current_user) do %>
                  <div class="comment-action">
                    <a class="reply-toggle"></a>
                    <div>
                      <a class="icon-reply"
                         data-toggle="tooltip"
                         data-placement="top"
                         title="评论">
                        <span class="glyphicon glyphicon-comment"
                              aria-hidden="true"></span>
                      </a>
                      <a class="icon-like"
                         data-toggle="tooltip"
                         data-placement="top"
                         title="赞">
                        <span class="glyphicon glyphicon-thumbs-up"
                              aria-hidden="true"></span>
                      </a>
                      <a class="icon-complait"
                         data-toggle="tooltip"
                         data-placement="top"
                         title="举报">
                        <span class="glyphicon glyphicon-alert"
                              aria-hidden="true"></span>
                      </a>
                      <%= if @current_user.id == comment.user_id do %>
                        <%= link [
                            to: post_comment_path(@conn,
                                :delete, @post.id,comment.id),
                            class: "",
                            method: "delete",
                            title: "删除",
                            data: [
                              confirm: "确定要删除？",
                              toggle: "tooltip"
                            ]] do %>
                          <span class="glyphicon glyphicon-trash"
                                aria-hidden="true"></span>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <% end %>

                <%= if length(comment.replies) > 0 do %>
                  <ul class="media-list reply-list">
                    <%= for reply <- comment.replies do %>
                      <li class="media">
                        <div class="reply-action">
                          <a class="reply-link"
                            data-reply-id="<%= reply.id %>"
                            data-user-nickname="<%= reply.user.nickname %>" >
                            回复</a>
                          <a>赞</a>
                        </div>
                        <div class="reply-body">
                          <%= link reply.user.nickname,
                              to: user_path(@conn, :show, reply.user),
                              class: "user-link"
                          %>
                          <%= if reply.reply_id do %>回复
                            <%= link reply.reply.user.nickname,
                              to: user_path(@conn, :show, reply.reply.user),
                              class: "user-link"
                            %>
                          <% end %>:
                          <%= reply.content %>
                        </div>
                      </li>
                    <% end %>
                  </ul>
                <% end %>

                <form class="reply-form"
                      action="<%= reply_path(@conn, :create, comment.id) %>"
                      method="POST">
                  <input name="_csrf_token"
                         type="hidden"
                         value="<%= get_csrf_token %>" >
                  <div class="form-group">
                    <textarea name="reply[content]"
                              class="form-control"></textarea>
                  </div>
                  <div class="form-group">
                    <%= submit "回复", class: "btn btn-primary" %>

                    <span class="replied-label">
                      <span class="glyphicon glyphicon-remove"
                            aria-hidden="true">
                      </span>
                      <span class="replied-nickname"></span>
                    </span>

                    <span class="error-info"></span>
                  </div>
                </form>
              </div>

            <% else %>
              <s>The comment is deleted.</s>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="no-item">QAQ 好无聊~ 还没有人来评论~</div>
    <% end %>

    <%= if @current_user do %>
      <%= form_for @changeset,
            post_comment_path(@conn, :create, @post.id), fn f -> %>
        <%= if @changeset.action do %>
          <div class="alert alert-danger">
            <p>Oops, something went wrong!Please check the errors below.</p>
          </div>
        <% end %>
        <div class="form-group">
          <%= textarea f, :content, class: "form-control simplemde" %>
          <%= error_tag f, :content %>
        </div>

        <div class="form-group">
          <label for="file" class="btn btn-default">上传</label>
          <%= submit "评论", class: "btn btn-primary" %>
        </div>
      <% end %>

      <%= form_for @conn, image_path(@conn, :create),
        [as: :upload,
         multipart: true,
         id: "upload-form",
         name: "upload"], fn f -> %>
        <div class="form-group">
          <%= file_input f, :file,
             id: "file",
             class: "form-control file-input" %>
        </div>
      <% end %>

    <% else %>

    <div class="panel panel-default">
      <div class="panel-body">
        需要
        <%= link "登录", to: session_path(@conn, :new),
              class: "btn btn-primary btn-xs" %>
        后才能评论，如果还没有账号，请进行
        <%= link "注册", to: user_path(@conn, :new),
              class: "btn btn-danger btn-xs" %>。
      </div>
    </div>
  <% end %>
  </div>
</div>

<div class="col-md-3">
</div>