web/router.ex
defmodule Exsite.Router do
  use Exsite.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Exsite.Auth, repo: Exsite.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/api", Exsite do
    pipe_through :api
    delete "/sessions/:user_id", SessionController, :delete
    post "/images", ImageController, :create
    post "/comments/:comment_id/replies", ReplyController, :create
  end

  scope "/", Exsite do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController,
      only: [:index, :show, :new, :create] do
      get "/:tab_key", UserController, :show, as: :tab
    end
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/topics", TopicController
    resources "/posts", PostController do
      resources "/comments", CommentController, only: [:create, :update, :delete]
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", Exsite do
  #   pipe_through :api
  # end
end

web/views/shared_view.ex
defmodule Exsite.SharedView do
  use Exsite.Web, :view
end

web/templates/shared/_comment_list.html.eex
<%= if @page.total_pages > 1, do: pagination_links @page %>

web/templates/shared/_new_post_button.html.eex
<%= if @current_user do %>
  <div class="panel">
    <%= link to:  post_path(@conn, :new) do %>
      <button class="btn btn-primary fullwidth">发布话题</button>
    <% end %>
  </div>
<% end %>

web/templates/shared/_post_list.html.eex
<ul class="media-list">
  <%= for post <- @page.entries do %>
    <li class="media">
      <div class="media-left media-top">
        <% link to: user_path(@conn, :show, post.user) do %>
          <img class="" alt="avatar">
        <% end %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= link post.title, to: post_path(@conn, :show, post) %></h4>
        <div>
          <small class="info">
            <%= link post.topic.name, to: topic_path(@conn, :show, post.topic_id), class: "topic-link" %>
            <%= link post.user.nickname, to: user_path(@conn, :show, post.user_id), class: "user-link" %>
            <%= time_formatter post.inserted_at %>
          </small>
        </div>
      </div>
      <div class="media-right media-middle">
        <%= link to: post_path(@conn, :show, post) do %>
          <div class="badge"><%= post.commentes_count %></div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

<%= if @page.total_pages > 1, do: pagination_links @page %>

web/templates/shared/_side_bar_links.html.eex
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">友情链接</h3>
  </div>
  <div class="list-group">
    <a class="list-group-item"
      href="https://ruby-china.org/"
      target="_blank">Ruby China
    </a>
    <a class="list-group-item"
      href="https://www.phoenix-china.org"
      target="_blank">PhoenixChina
    </a>
  </ul>
</div>